# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_us_ex.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 576)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 541, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.current_moment = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.current_moment.setGeometry(QtCore.QRect(13, 30, 771, 411))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.current_moment.setFont(font)
        self.current_moment.setReadOnly(True)
        self.current_moment.setObjectName("current_moment")
        self.confButton = QtWidgets.QPushButton(self.centralwidget)
        self.confButton.setGeometry(QtCore.QRect(10, 440, 121, 61))
        self.confButton.setObjectName("confButton")
        self.monitorButton = QtWidgets.QPushButton(self.centralwidget)
        self.monitorButton.setGeometry(QtCore.QRect(130, 440, 111, 61))
        self.monitorButton.setObjectName("monitorButton")
        self.installButton = QtWidgets.QPushButton(self.centralwidget)
        self.installButton.setGeometry(QtCore.QRect(240, 440, 111, 61))
        self.installButton.setObjectName("installButton")
        self.currentButton = QtWidgets.QPushButton(self.centralwidget)
        self.currentButton.setGeometry(QtCore.QRect(350, 440, 131, 61))
        self.currentButton.setObjectName("currentButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.open = QtWidgets.QMenu(self.menubar)
        self.open.setObjectName("open")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.monitor = QtWidgets.QAction(MainWindow)
        self.monitor.setObjectName("monitor")
        self.conf = QtWidgets.QAction(MainWindow)
        self.conf.setObjectName("conf")
        self.Smart = QtWidgets.QAction(MainWindow)
        self.Smart.setObjectName("Smart")
        self.open.addAction(self.monitor)
        self.open.addAction(self.conf)
        self.menubar.addAction(self.open.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UsEXHelper"))
        self.label.setText(_translate("MainWindow", "Информация о компьютере"))
        self.confButton.setText(_translate("MainWindow", "Создать\n"
" конфигурационный\n"
"файл"))
        self.monitorButton.setText(_translate("MainWindow", "Запустить\n"
"мониторинг"))
        self.installButton.setText(_translate("MainWindow", "Скачать список\n"
"необходимых\n"
"программ"))
        self.currentButton.setText(_translate("MainWindow", "Показать информацию\n"
"о текущем компьютере"))
        self.open.setTitle(_translate("MainWindow", "Открыть"))
        self.monitor.setText(_translate("MainWindow", "Файл мониторинга"))
        self.conf.setText(_translate("MainWindow", "Файл конфигурации"))
        self.Smart.setText(_translate("MainWindow", "Анализ жестких дисков"))
